# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sn6gwdumgrNG3--n0RBK5YdXJn8KL2Xc
"""

import numpy as np

tamanho_array = 1000
numeros_aleatorios = np.random.randint(97, 123, tamanho_array)
array_aleatorio = [chr(numero) for numero in numeros_aleatorios]
array_ordenado = np.sort(array_aleatorio)



print(array_ordenado)